name: Run Content_Manager Test
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Test Content Manager"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: '100s'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Install content_manager
        run: pip install -r tools/content_manager/requirements.txt
      - name: Run tests using pytest
        run: pytest -v
      - name: Verify YARA-L rules
        # Verify that all rules are valid YARA-L 2.0 rules via Google SecOps' API
        run: content_manager rules verify --path ./rules/
